# Ejercicios labo 2

## Ejercicio 1 (Reescalamiento). Si consideramos la transformaci ́on lineal
(x,y) = T{(w,z)}= (2w,3z),
Se pide:
1. Encontrar la expresi ́on de la matriz T y T−1.
2. Usar estas transformaciones para aplicarlas en los vectores can ́onicos, a
un punto arbitrario y a una circunferencia. ¿Qu ́e sucede en cada caso?

T(1,0) = (2*1,0)

T(0,1) = (0,3*1)

In [10]:
T = [ 
    [2,0], 
    [0,3]
    ]
import numpy as np
T_inv = np.array([
    [1/2,0],
    [0,1/3]
])

(2, 2)

In [14]:
np.zeros(T_inv.shape)

array([[0., 0.],
       [0., 0.]])

In [ ]:
T = np.array([
    [2,0],
    [0,2]
])
puntos = np.array([
    [1,1,4,3],
    [2,3,4,1]
])
assert(T.shape == (2,2))  # chequeo de matriz 2x2
assert(T.shape[1] == puntos.shape[0]) # multiplicacion matricial valida   
punto_transformados = np.zeros(puntos.shape)
cant_puntos = puntos.shape[1]
############### Insert code here!! ######################3    
for n_punto in range(cant_puntos):
    x = puntos[0,n_punto]
    y = puntos[1,n_punto]
    nuevo_x,nuevo_y = (T@np.array([x,y]))
    punto_transformados[0,n_punto] = nuevo_x
    punto_transformados[1,n_punto] = nuevo_y
print(punto_transformados)
############### Insert code here!! ######################3

[[2. 2. 8. 6.]
 [4. 6. 8. 2.]]


In [38]:
T = np.array([
    [1,2,3,5], 
    [3,4,5,9]
])

In [44]:
T.shape

(2, 4)

## Ejercicio 3

Ejercicio 3. Escribir la matriz de las siguientes transformaciones lineales en
base can ́onica. Interpretar geom ́etricamente cada transformaci ́on.

(a) f(x,y) = (x,−y)
f(1,0) = (1,0)
f(0,1) = (0,-1)

(b) f(x,y) = ( 1/2 (x −y), 1/2 (x − y))
f(1,0) = 0.5, 0.5
f(0,1) = -0-5 , -0.5 


In [ ]:
T_b = [
    []
]